version: '3.3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  tor:
    image: dperson/torproxy
    ports:
      - 8120:8118
  #  networks:
  #      - internal
  app:
    build:
      context: .
    image: tomcat-test
    env_file: docker-compose.env
    depends_on:
      - redis
